FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy ALL workspace files (they'll be overwritten by volume mounts for src)
COPY . .

# Install dependencies
RUN pnpm install

EXPOSE 3000

WORKDIR /app/apps/frontend
CMD ["pnpm", "dev"]
