name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker Compose
        - Docker (manual)
        - Local development (pnpm dev)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you running? (Check package.json or git commit)
      placeholder: e.g., 0.1.0 or commit hash

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant logs from the browser console or backend.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, environment details, etc.)
