name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of Logarr does this affect?
      options:
        - Dashboard
        - Log Viewer
        - Issue Tracking
        - AI Analysis
        - Session Monitoring
        - Sources/Server Management
        - Settings
        - API
        - New Provider (Plex, Emby, etc.)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or any other context that helps explain the feature.
